### ISSUE TITLE
Duplicated Toolbar on Re-render

### ISSUE THREAD

**Issue by guilhermeslk** [andreioprisan/meteor-bootstrap3-wysihtml5#2]
![captura de tela de 2014-01-13 16 13 55](https://f.cloud.github.com/assets/2680966/1903229/7fe3fd32-7c7e-11e3-81b3-588b6ba92b2c.png)

I'm getting multiple toolbars after re-rendering the template.

**Comment by andreioprisan** [comment]
Interesting, I can't reproduce. What browser and version do you use?

**Comment by jbl2024** [comment]
Hi,
same problem here with chrome 32.0.1700.102 (mac), Template.rendered is called twice when reloading page.

**Comment by rglover** [comment]
@guilhermeslk @jbl2024 I ran into this too and found an easy fix. You'll want to take the markup that wysihtml5 is being called on and put it into its own template. The double render happens (for myself, at least) because I'm loading data into the same template where the wysihtml5 textareas exist. For example, instead of:

```
<template name='parentTemplate'>
  <!-- A piece of reactive data that may cause a re-render on the parent -->
 {{#each sandwiches}}
   <p>{{name}} - {{flavor}}</p>
 {{/each}}
 <textarea class="textarea></textarea>
</template>
```

Do something like:

```
<template name="parentTemplate">
  <!-- A piece of reactive data that may cause a re-render on the parent -->
 {{#each sandwiches}}
   <p>{{name}} - {{flavor}}</p>
 {{/each}}
 {{>textareaTemplate}}
</template>

<template name="textareaTemplate">
 <textarea class="textarea"></textarea>
</template>
```

This isolates the textarea rendering to itself. Then, just write a rendered function for the new template:

```
Template.textareaTemplate.rendered = function() {
 // Initialize wysihtml5
 $('.textarea').wysihtml5();
}
```

Beyond that, not sure if there's a check that can be done to see if the plugin is already applied to the dom...

**Comment by guilhermeslk** [comment]
Thank you @rglover! 
That worked fine! Problem solved!

**Comment by gustavobotega** [comment]
@rglover  which file you changed?

**Comment by themeteorchef** [comment]
@gustavobotega see code snippets above. In order to prevent the duplication, you need to put the textarea element that is having the wysiwyg controls prepended to it in its own template. So, instead of something like: 

```
<template name='parentTemplate'>
  <!-- A piece of reactive data that may cause a re-render on the parent -->
 {{#each sandwiches}}
   <p>{{name}} - {{flavor}}</p>
 {{/each}}
<!-- The element below is the one we need to move into a separate template -->
 <textarea class="textarea></textarea>
</template>
```

we need to do this:

```
<template name="parentTemplate">
  <!-- A piece of reactive data that may cause a re-render on the parent -->
 {{#each sandwiches}}
   <p>{{name}} - {{flavor}}</p>
 {{/each}}
 {{>textareaTemplate}}
</template>

<template name="textareaTemplate">
 <textarea class="textarea"></textarea>
</template>
```

The difference is that instead of having everything inside of `parentTemplate`, we've separated the `<textarea>` into its own template `textareaTemplate`. Keep in mind, the specific location/placement of this will depend on your application. The only thing that matters is that you separate the textarea into its own template.
